spring:
  application:
    name: yu-ai-code-mother-backend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://175.27.255.222:3306/yu_ai_code_mother
    username: ai_code
    password: 050312+Qq
  data:
    redis:
      host: 175.27.255.222
      port: 6379
      password: root
      ttl: 3600
server:
  port: 8123
  servlet:
    context-path: /api

# springdoc-openapi
springdoc:
  group-configs:
    - group: 'default'
      packages-to-scan: com.yuaicodemother.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn
# AI
langchain4j:
  open-ai:
    chat-model:
      base-url: https://api.deepseek.com
      api-key: sk-9d247236bcda43098d94c9cd53880f3b
      model-name: deepseek-chat
      log-requests: true
      log-responses: true
      max-tokens: 8192
      strict-json-schema: true
      response-format: json_object
    streaming-chat-model:
      base-url: https://api.deepseek.com
      api-key: sk-9d247236bcda43098d94c9cd53880f3b
      model-name: deepseek-chat
      max-tokens: 8192
      log-requests: true
      log-responses: true
